In [ ]:
''' NUMPY IS USED AS LIBRARY IN PYTHON.
NUMPY INSTALL VIA PIP INSTALL NUMPY.
USED TO WORK WITH ARRAY.
USED AS SHORT FOR NUMERIC PYTHON.
NUMPY IS FASTER THAN LIST.'''

In [1]:
import numpy as np
arr=(1,2,3,4,5,6,7,8,9,10)
print(arr)

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)


In [8]:
import numpy as np
arr=np.array(['devanshu','rutvi','jadav','rahul','meet','jay'])
print(arr)

['devanshu' 'rutvi' 'jadav' 'rahul' 'meet' 'jay']


In [7]:
import numpy as np
arr=np.array(['devanshu','rutvi','jadav','rahul','meet','jay'])
print(type(arr))

<class 'numpy.ndarray'>


In [9]:
import numpy as np
arr=np.array(['devanshu','rutvi','jadav','rahul','meet','jay'])
print(arr[2])

jadav


In [10]:
import numpy as np
print(np.__version__)   # TO CHECK THE VERSION.---> 2 TIMES _ _

2.4.0


In [12]:
'''NUMPY BASICALLY USED FOR ARRAY.
NUMPY CREATE AN ARRAY OBJECT I.E CALLED NDARRAY.
NDARRAY OBJECT BY USING ARRAY() FUNCTION.'''
import numpy as np
a=np.array(['vijay','rahul','jay','geet','meet','aayushi'])
print(a)
print(type(a))

['vijay' 'rahul' 'jay' 'geet' 'meet' 'aayushi']
<class 'numpy.ndarray'>


In [14]:
# USE TUPLE TO CREATE A NUMPY ARRAY USING ARRAY():-
import numpy as np
a=np.array((1,2,3,4,5,6))         # TUPLE MUST BE GIVEN IN () OF ARRAY.
print(a)
print(type(a))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [ ]:
'''USING DIMENSION IN ARRAY:-
TYPES OF DIMENSION IN ARRAY(NUMPY):-
0--> DIMENSION
1--> DIMENSION
2--> DIMENSION'''

In [15]:
# 0 DIMENSION ARRAY:-(JUST 1 VALUE, NO ROW, NO COLUMNS)
import numpy as np
arr=np.array(17)
print(arr)

17


In [18]:
# 1-DIMENSION ARRAY:-
b=np.array([1,2,3,4,5])
print(b)
print(b.ndim)       # ndim means how much dimension is there.

[1 2 3 4 5]
1


In [20]:
#2-DIMENSION ARRAY:-
c=np.array([[1,2,3,4],[5,6,7,8]])    # YOU HAVE TO GIVE IN PERTICULAR ORDER N=MEANS [4-VALUES],[4-VALUES]
print(c)
print(c.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [24]:
#2-DIMENSION ARRAY:-
c=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(c)
print(c.ndim)   # YOU CANNOT GIVE 2-DIMENSION.

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2


In [27]:
#2-DIMENSION ARRAY:-
c=np.array([[1,2],[5,6],[9,10],[12,15]])   # VALUES MUST BE SAME IN EACH[].
print(c)
print(c.ndim)

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [12 15]]
2


In [29]:
#3-DIMENSION ARRAY:-
c=np.array([[[1,2],[5,6],[9,10],[12,15]]])
print(c)
print(c.ndim)

[[[ 1  2]
  [ 5  6]
  [ 9 10]
  [12 15]]]
3


In [3]:
#ACCESSING ELEMENT OF ARRAYS:-
import numpy as np
c=np.array([1,2,3,4,5,6,7])
print(c[3]+c[4])

9


In [6]:
#SLICING OF ARRAY:-
import numpy as np
c=np.array([1,2,3,4,5,6,7])
print(c[::-1])
print(c[1:3])

[7 6 5 4 3 2 1]
[2 3]


In [7]:
# RETURNS A DATA TYPE:-
import numpy as np
c=np.array([1,2,3,4,5,6,7])
print(c.dtype)

int64


In [8]:
# RETURNS A DATA TYPE:-
import numpy as np
c=np.array(['devanshu','vijay','rajesh'])
print(c.dtype)                  # <U8---> STRING.

<U8


In [14]:
# COPY MAKE A COPY OF ARRAY:-
a=np.array([1,2,3,4,5,6,7,8,9,10])
a[0]=90
b=a.copy()
b[2]=99
print(b)

[90  2 99  4  5  6  7  8  9 10]


In [15]:
#VIEW IS USED TO CHANGE THE VIEW AND DISPLAY BOTH ARRAY:-
import numpy as np
a=np.array([1,2,3,4,5,6])
b=a.view()
b[0]=10
print(a,b)

[10  2  3  4  5  6] [10  2  3  4  5  6]


In [16]:
#ARRAY ITERATING VIA NUMPY:-
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
for i in a:                      # I IS USED TO FETCH 1 ELEMENT AT A TIME.
    print(i)

1
2
3
4
5
6
7
8
9
10


In [22]:
#JOINING NUMPY ARRAY:-(1-D ARRAY)
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
res=np.concatenate((a,b))
print(res)

[ 1  2  3  4  5  6  7  8  9 10]


In [23]:
#JOINING NUMPY ARRAY:-(2-D ARRAY)
a=np.array([[1,2,3,4,5]])
b=np.array([[6,7,8,9,10]])
res=np.concatenate((a,b))
print(res)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [24]:
#JOINING NUMPY ARRAY:-(3-D ARRAY)
a=np.array([[[1,2,3,4,5]]])
b=np.array([[[6,7,8,9,10]]])
res=np.concatenate((a,b))
print(res)

[[[ 1  2  3  4  5]]

 [[ 6  7  8  9 10]]]


In [25]:
#SPLITING OF ARRAY:-
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10])
res=np.array_split(a,4)                   # np.array_split(a,parts_you_want_to_split)
print(res)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8]), array([ 9, 10])]


In [27]:
#SEARCHING OF ARRAY:-
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10,3,9,10,2,3,0,100,3])
res=np.where(a==3)
print(res)

(array([ 2, 10, 14, 17]),)


In [28]:
# SEARCHING WITH SORTED:-
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10,3,9,10,2,3,0,100,3])
res=np.searchsorted(a,3)
print(res)

2


In [60]:
#FILTERS ARRAY:-
import numpy as np
a=np.array([91,92,93,94,95])
filt=a>92             # filt is variable.
res=a[filt]
print(res)

[93 94 95]


In [72]:
# FIND THE RANDOM VALUE FROM 0 TO 100:-
from numpy import random
a=random.randint(100, size=(5))   # rand int is for integer.
print(a)

[37 14 86  8 85]


In [76]:
#SHUFFLE:-
from numpy import random
a=np.array([1,2,3,4,5,6,7,8,9,10])
random.shuffle(a)
print(a)

[ 1  8  4  9  5  7  2  3  6 10]
