In [ ]:
'''WHAT IS ARRAY ??
-ARRAY IS A PART OF DATA STRUCTURE AND COLLECTIONS IN PYTHON.
-ARRAYIS COLLECTION OF MULTIPLE DATA STORED IN SINGLE VARIABLE.
-IN PYTHON ARRAY IS USED AS LIST[].
-EVERY FUNCTION USED IN LIST IS USED FOR ARRAY ALSO.
-PYTHON DO NOT SUPPORT BUILT-IN ARRAY DATA TYPE.
-PYTHON SUPPORT ARRAY VIA NUMPY LIBRARY.

In [2]:
emp=["devanshu",'rajesh',1,2,3,4,5]
print(emp)
print(type(emp))   #PYTHON DO NOT SUPPORT BUILT-IN ARRAY DATA TYPE.

['devanshu', 'rajesh', 1, 2, 3, 4, 5]
<class 'list'>


In [6]:
#PYTHON NOT USE ARRAY BUT CAN TAKE FROM NUMPY LIBRARY.
import numpy as np
res=np.array(['devanshu','ruhi','vijay',1,2,3,4,5])
print(res)
print(type(res))

['devanshu' 'ruhi' 'vijay' '1' '2' '3' '4' '5']
<class 'numpy.ndarray'>


In [8]:
#MULTIDIMENTIONAL ARRAY:-(ARRAY WITHIN ANOTHER ARRAY)
import numpy as np
a=np.array([[1,2,],['devanshu','vijay'],['suraj','flower']])   # ARRAY WITHIN ARRAY.
print(a)

[['1' '2']
 ['devanshu' 'vijay']
 ['suraj' 'flower']]


In [9]:
import numpy as np
res=np.array([1,2,3,4,5])
print(res*2)
print(type(res))

[ 2  4  6  8 10]
<class 'numpy.ndarray'>


In [10]:
import numpy as np
res=np.array([1,2,3,4,5])
print(res/2)
print(type(res))

[0.5 1.  1.5 2.  2.5]
<class 'numpy.ndarray'>


In [11]:
import numpy as np
res=np.array([1,2,3,4,5])
print(res+22)
print(type(res))

[23 24 25 26 27]
<class 'numpy.ndarray'>


In [12]:
#ACCESSING THE ARRAY:-(TAKING PERTICULAR VALUE)
import numpy as np
res=np.array(['devanshu','vijay','mahipal'])
print(res[2])

mahipal


In [23]:
#APPEND IN ARRAY:-(ADDING IN ARRAY)
import numpy as np
res=np.array(['devanshu','vijay','mahipal'])
res1=np.append(res,4)   # res,4 res is variable taken in 3rd line.
res1=np.append(res,"rutvi")
print(res1)

['devanshu' 'vijay' 'mahipal' 'rutvi']


In [24]:
#APPEND MULTIPLE VALUE IN ARRAY:-(ADDING MULTI VALUES)
import numpy as np
res=np.array(['devanshu','vijay','mahipal'])
res1=np.append(res,4)   # res,4 res is variable taken in 3rd line.
res1=np.append(res,["rutvi",'veer'])
print(res1)

['devanshu' 'vijay' 'mahipal' 'rutvi' 'veer']


In [31]:
# ADD NEW ELEMENT IN ARRAY INSERT():-
import numpy as np
a=np.array(['dev','raj','jay','hero','suraj'])
a=np.insert(a,5,'rutvi')    # (variable_name,index,new_value)
print(a)

['dev' 'raj' 'jay' 'hero' 'suraj' 'rutvi']


In [36]:
# REMOVE ELEMENT IN ARRAY:-
import numpy as np
a=np.array(['dev','raj','jay','hero','suraj'])
a=np.delete(a,3)             # DELETE(VARIABLE_NAME,INDEXING)
print(a)

['dev' 'raj' 'jay' 'suraj']


In [38]:
# REMOVE PERTICULAR ELEMENT IN ARRAY:-
import numpy as np
a=np.array(['dev','raj','jay','hero','suraj'])
a=np.delete(a,np.where(a=='suraj'))            # DELETE(VARIABLE_NAME,np.where-tofind(variable_name=="name"))
print(a)

['dev' 'raj' 'jay' 'hero']


In [39]:
# REVERSE ANY ARRAY:-
import numpy as np
a=np.array(['dev','raj','jay','hero','suraj'])
a=a[::-1]
print(a)

['suraj' 'hero' 'jay' 'raj' 'dev']
