In [ ]:
#.2 Get the common items between a and b :-

In [5]:
#USING SET BUT WITHOUT KEEPING ORDER:-
a=(1,2,3,4,5)
b=(3,4,5,6,7)
common=list(set(a) & set(b))
print(common)

[3, 4, 5]


In [7]:
# JUST BY KEEPING ORDER:-
a=(1,2,3,4,5,6,7,8,9,10)
b=(2,4,6,8,10,12,14,16)
common=[x for x in a if x in b]
print(common)

[2, 4, 6, 8, 10]


In [9]:
#EXAMPLES WITH NUMPY ARRAY:-
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([3,4,5,6,7])
c=np.intersect1d(a,b)
print(c)

[3 4 5]


In [12]:
# with duplicates:-
import numpy as np
a=np.array([1,2,2,3,4,4,5])
b=np.array([2,3,5,7,9])
common=a[np.isin(a,b)]      #only np.isin(a,b) :- return boolean values. a is array which we want to filter.
print(common)

[2 2 3 5]


In [17]:
# 2-D examples:-
a=np.array([[1,2,2,3,4,4,5],       # BOTH 2-D MUST HAVE SAME ELEMENTS IN IT([[SAME],[SAME]])
            [6,7,7,9,10,11,12]])
b=np.array([2,3,5,7,9])
common=a[np.isin(a,b)]
print(common)

[2 2 3 5 7 7 9]


In [19]:
#3-D EXAMPLES:-
a=np.array([[[1,2,2,3,4,4,5],
            [6,7,7,9,10,11,12],
             [13,14,15,16,17,18,19]]])
b=np.array([[2,3,5,7,9],
          [11,12,13,1,19]])
common=a[np.isin(a,b)]
print(common)

[ 1  2  2  3  5  7  7  9 11 12 13 19]
